project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Ex"
        menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
      
      - text: "In-class Ex"
        menu: 
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01a.html"
        - text: "In-class Exercise 2"
          href: "https://public.tableau.com/app/profile/jiayi.li4640/viz/In-classex02/MonthlySalesandProfitsbyRegion2016-2019"
      
      - text: "Take-home Ex"
        menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
        - text: "Take-home Exercise 4"
          href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
      
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
    

format:
  html:
    theme: 
      - simplex
      - custom.scss
    mermaid:
      theme: neutral
    
    css: styles.css
    toc: true
    fontsize: 90%
    linestretch: 1.6
    # backgroundcolor: rgb(246, 245, 244)
    monobackgroundcolor: rgb(255, 255, 255)

